import requests
from bs4 import BeautifulSoup
import re
import smtplib
import time

URL = 'https://www.edx.org/professional-certificate/uc-berkeleyx-blockchain-fundamentals'
#URL of the site you need to scrap the price from

headers = {"User-Agent": 'My user-agent'}
#google my user-agent and copy paste here

def check_price():
    page = requests.get(URL, headers = headers)

    soup = BeautifulSoup(page.content, 'html.parser')

    title = soup.find('div', {"class": "title"}).text
    price = soup.find('div', {"class": "main d-flex flex-wrap"}).text
    # but we need to convert the price into integer, so we need to use regex

    x= re.findall("[0-9]+",price)
    for i in x:
        i = int(i)
        break
    # to get the first price

    if(i < 100):
        send_email()

def send_email():
    #we need to establish a connection between our conn and gmail's conn
    server = smtplib.SMTP('smtp.gmail.com', 587)
    
    server.ehlo() 
    #Extended HELO (EHLO) is an Extended Simple Mail Transfer Protocol (ESMTP) command sent by an email server 
    #to identify itself when connecting to another email server to start the process of sending an email
    
    server.starttls() 
    #encrypts our conn

    server.ehlo()

    server.login('sender mail addr', 'password')
    #here password is the one generated by google app password for windown computer. You need to enable google 2 factor authentication
    #or google less secure apps to do this

    subject = "Hey the price fell down!!! Lets buy it right now"
    body = "Check the course link https://www.edx.org/professional-certificate/uc-berkeleyx-blockchain-fundamentals"

    msg = f"Subject : {subject}\n\n{body}"
    
    server.sendmail(
        'sender mail addr', #from addr
        'reciever mail addr', #to_addr
        msg
    )

    print("hey email is sent!")

    server.quit()

while(True):

    check_price()
    time.sleep(60*60*24) #once in a day